import "./globals.css";
import type { Metadata } from "next";
import { Nav } from "@/lib/components/Nav";
import logo from "../public/logo2.webp";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Nav
          activeLink="accent"
          logo={logo}
          fill="primary"
          navLinks={[
            { path: "/", name: "Home" },
            { path: "/about", name: "About" },
            { path: "/about", name: "About" },
            { path: "/about", name: "About" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
